### ISSUE TITLE
Npm install is not working properly

### ISSUE THREAD

**Issue by avneet2112** [enescang/react-pdf-table#1]
There is no backgroundColor props even after I installed the latest version of the package. Can you please look into it
You can try the same but run npm i react-pdf-table in another project

**Comment by david-kironde-deel** [comment]
Facing similar issue.

**Comment by enescang** [comment]
I have published new version: https://github.com/enescang/react-pdf-table/commit/b95cdd96896f71616681ee4e441adb9ab803558a

NPM: https://www.npmjs.com/package/react-pdf-table/v/1.0.0-alfa.3
